server:
  port: 7000
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.101.143.30:8848
#        server-addr: nacos
    gateway:
      routes:
        - id: service-position
          uri: lb://service-position
          predicates:
            - Path=/position/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/user/**
        - id: service-status
          uri: lb://service-status
          predicates:
            - Path=/status/**
        - id: service-vacation
          uri: lb://service-vacation
          predicates:
            - Path=/vacation/**
      globalcors: # 网关cors跨域设置
        corsConfigurations:
          '[/**]': # gateway网关上所有的uri都应用下面的跨域设置
            allowCredentials: true # 允许携带认证信息
            allowedOrigins:
              - "*" # 允许所有来源进行跨域访问
            allowedHeaders: "*" # 允许跨域请求里的head字段，设置为*是全部
            allowedMethods: # 允许跨域的方法
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            max-age: 3600