spring:
  application:
    name: service-vacation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/covid?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
#    url: jdbc:mysql://mysql/covid?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    hikari:
      max-lifetime: 500000
  cloud:
    nacos:
      discovery:
        server-addr: 47.101.143.30:8848
#        server-addr: nacos
mybatis:
  mapper-locations:  classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8021